// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";



const url = process.env.TURSO_DATABASE_URL || process.env.DATABASE_URL;
const authToken = process.env.TURSO_AUTH_TOKEN;

// Prisma CLI needs the auth token physically present in the connection string to push to LibSQL remotely
const formattedUrl = url?.includes("turso.io") && authToken 
  ? `${url}?authToken=${authToken}` 
  : url;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: formattedUrl,
  },
});
